<?php

declare(strict_types=1);

namespace Nowo\MaintenanceModeBundle\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\ArrayNodeDefinition;
use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

use function is_bool;

/**
 * Bundle configuration tree under alias `nowo_maintenance_mode`.
 */
final class Configuration implements ConfigurationInterface
{
    public const ALIAS = 'nowo_maintenance_mode';

    public function getConfigTreeBuilder(): TreeBuilder
    {
        $treeBuilder = new TreeBuilder(self::ALIAS);
        /** @var ArrayNodeDefinition $rootNode */
        $rootNode = $treeBuilder->getRootNode();

        $rootNode
            ->info('Nowo Maintenance Mode Bundle configuration.')
            ->children()
                ->booleanNode('enabled')
                    ->info('Master switch: when false the subscriber never returns 503.')
                    ->defaultTrue()
                ->end()
                ->scalarNode('default_message')
                    ->info('Default message shown on the public maintenance page. null = rely on Twig translation (maintenance.page.message).')
                    ->defaultValue("We're making a few gentle improvements. Everything you care about is safe.")
                ->end()
                ->integerNode('status_code')
                    ->info('HTTP status code for the maintenance response.')
                    ->defaultValue(503)
                    ->min(400)
                    ->max(599)
                ->end()
                ->integerNode('retry_after')
                    ->info('Retry-After header value in seconds.')
                    ->defaultValue(3600)
                    ->min(0)
                ->end()
                ->integerNode('subscriber_priority')
                    ->info('kernel.request listener priority (default 31: after router so route/controller exclusions work).')
                    ->defaultValue(31)
                ->end()
                ->arrayNode('preview')
                    ->info('Dev preview of the configured public maintenance page (like /_error/503).')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->variableNode('enabled')
                            ->info('null = enable when kernel.debug is true. Set false to disable even in debug.')
                            ->defaultNull()
                            ->validate()
                                ->ifTrue(static fn (mixed $v): bool => $v !== null && !is_bool($v))
                                ->thenInvalid('preview.enabled must be null or a boolean.')
                            ->end()
                        ->end()
                        ->scalarNode('path')
                            ->info('URL path for the preview (auto-excluded from 503).')
                            ->defaultValue('/_maintenance_preview')
                            ->cannotBeEmpty()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('panel')
                    ->info('Admin CRUD panel settings.')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')
                            ->info('Expose the Twig CRUD panel controllers.')
                            ->defaultTrue()
                        ->end()
                        ->scalarNode('path_prefix')
                            ->info('URL prefix for the panel routes (also auto-excluded from 503).')
                            ->defaultValue('/_maintenance')
                            ->cannotBeEmpty()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('exclusions')
                    ->info('Requests matching any rule bypass the maintenance page.')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->arrayNode('paths')
                            ->info('Exact path matches (e.g. /health).')
                            ->scalarPrototype()->end()
                            ->defaultValue([])
                        ->end()
                        ->arrayNode('path_prefixes')
                            ->info('Path prefixes (e.g. /api/health). Panel prefix is always added.')
                            ->scalarPrototype()->end()
                            ->defaultValue([])
                        ->end()
                        ->arrayNode('routes')
                            ->info('Route names that bypass maintenance.')
                            ->scalarPrototype()->end()
                            ->defaultValue([])
                        ->end()
                        ->arrayNode('patterns')
                            ->info('Glob (fnmatch) or regex (#…# or ~…~) patterns against the request path.')
                            ->scalarPrototype()->end()
                            ->defaultValue([])
                        ->end()
                        ->arrayNode('ips')
                            ->info('Client IPs or CIDR ranges that bypass maintenance (configure framework.trusted_proxies when behind a proxy).')
                            ->scalarPrototype()->end()
                            ->defaultValue([])
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('security')
                    ->info('Panel access gate + soft bypass for QA. Replace the gate service for a custom voter/authenticator.')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('password_protection')
                            ->info('When false, the panel login section is disabled even if a hash is set (trusted networks only).')
                            ->defaultTrue()
                        ->end()
                        ->scalarNode('password_hash')
                            ->info('password_hash() output (bcrypt / argon2id / sodium). Prefer env: MAINTENANCE_PASSWORD_HASH.')
                            ->defaultNull()
                        ->end()
                        ->scalarNode('access_gate')
                            ->info('FQCN or service id implementing MaintenanceAccessGateInterface. null = default password gate.')
                            ->defaultNull()
                        ->end()
                        ->scalarNode('bypass_token')
                            ->info('Optional shared secret: ?maintenance_bypass=TOKEN (or cookie) skips the 503 for QA without opening the panel.')
                            ->defaultNull()
                        ->end()
                        ->scalarNode('bypass_query_parameter')
                            ->info('Query parameter name for the soft bypass token.')
                            ->defaultValue('maintenance_bypass')
                            ->cannotBeEmpty()
                        ->end()
                        ->scalarNode('bypass_cookie_name')
                            ->info('Cookie name set after a successful query bypass.')
                            ->defaultValue('nowo_maintenance_bypass')
                            ->cannotBeEmpty()
                        ->end()
                        ->booleanNode('bypass_set_cookie')
                            ->info('When true, a successful query bypass also sets a cookie for subsequent requests.')
                            ->defaultTrue()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('storage')
                    ->info('Pluggable state / history backends (default: filesystem under var/).')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('state_file')
                            ->info('JSON or YAML file for MaintenanceState.')
                            ->defaultValue('%kernel.project_dir%/var/maintenance/state.json')
                        ->end()
                        ->scalarNode('history_file')
                            ->info('Append-only JSONL history file.')
                            ->defaultValue('%kernel.project_dir%/var/maintenance/history.jsonl')
                        ->end()
                        ->scalarNode('state_storage')
                            ->info('Override service id / FQCN for MaintenanceStateStorageInterface.')
                            ->defaultNull()
                        ->end()
                        ->scalarNode('history_storage')
                            ->info('Override service id / FQCN for MaintenanceHistoryStorageInterface.')
                            ->defaultNull()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('templates')
                    ->info('Overrideable Twig templates (REQ-TWIG).')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('page')
                            ->defaultValue('@NowoMaintenanceModeBundle/maintenance/page.html.twig')
                        ->end()
                        ->scalarNode('panel_layout')
                            ->defaultValue('@NowoMaintenanceModeBundle/panel/layout.html.twig')
                        ->end()
                        ->scalarNode('panel_index')
                            ->defaultValue('@NowoMaintenanceModeBundle/panel/index.html.twig')
                        ->end()
                        ->scalarNode('panel_login')
                            ->defaultValue('@NowoMaintenanceModeBundle/panel/login.html.twig')
                        ->end()
                        ->scalarNode('panel_history')
                            ->defaultValue('@NowoMaintenanceModeBundle/panel/history.html.twig')
                        ->end()
                    ->end()
                ->end()
            ->end();

        return $treeBuilder;
    }
}
