# Default Flex recipe config.
nowo_maintenance_mode:
    enabled: true
    default_message: 'We're making a few gentle improvements. Everything you care about is safe.'
    panel:
        enabled: true
        path_prefix: '/_maintenance'
